# Generated by Django 3.0.5 on 2020-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Service_model',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Office', 'Office'), ('Residential', 'Residential')], max_length=200, null=True),
        ),
    ]
